### ISSUE TITLE
[Question] Display definition

### ISSUE THREAD

**Issue by mantielero** [gkv311/occt-hello#2]
https://github.com/gkv311/occt-hello/blob/ee542b8f3ccd631de686ebbb2fe193453d6754db/occt-ais-hello/OcctAisHello.cpp#L171

Where is `Display` defined in the API? I'm not finding it.

**Comment by gkv311** [comment]
'Display' belongs to X11.
https://www.x.org/releases/X11R7.6/doc/libX11/specs/libX11/libX11.html#display_functions

**Comment by mantielero** [comment]
Thanks for this. I am closing the question, but I will probably open another one more general in order to avoid bothering you with many issues.
