### ISSUE TITLE
[Question] Support related for Nim wrapper

### ISSUE THREAD

**Issue by mantielero** [gkv311/occt-hello#3]
I am trying to implement an OpenCascade wrapper for the Nim programming language. So far I managed to do significant progress (given that I develop as a hobby), but I am struggling with the visualization part.

As a first step I am trying to implement a bare minimum example. For that regard, [occt-ais-hello](https://github.com/gkv311/occt-hello/tree/master/occt-ais-hello) is becoming very useful for me. By minimum, I mean just showing a solid even if it does not react to events.

Right now I only get a window, but it displays nothing inside it:
![](https://i.imgur.com/JsjEPcN.png)

The Nim code I am using is [here](https://github.com/mantielero/occt.nim/blob/main/examples/viewer04.nim). It is quite understandable.

I couldn't create a constructor. So I create an object based on `AIS_ViewController` with the fields `myContext` and `myView`. Then I create the function `getContextAndView`, which I used in [this line](https://github.com/mantielero/occt.nim/blob/300e5057e3c46ffb9e770d3c280c4ac0f7c2aacf/examples/viewer04.nim#L74) in order to populate the fields in `aViewer` instance.

I am on OCCT 8.5, by the way, under ArchLinux.

Nim creates C++ code. In this case, the C++ file created is [this one](https://pastebin.com/uaAneVnb). 

I know it is difficult, but can you spot any significant miss that prevents the box from being shown?

**Comment by gkv311** [comment]
```
  #var anXDisplayPtr:Display = getDisplay( `*`(aDispConn) )
  while true:
    discard

main()
```
Your code doesn't implement any X11 event loop.
Try combining some X11 sample for nim (like [this](https://github.com/nim-lang/x11/blob/master/examples/x11ex.nim) ) with event loop from viewer sample (redirecting `XNextEvent` to `Xw_Window::ProcessMessage`)

**Comment by mantielero** [comment]
Understood and thanks a lot for taking your time. Is there any equivalent for `ProcessMessage` for OpenCascade v8.5?

**Comment by gkv311** [comment]
> for OpenCascade v8.5?

Such version doesn't yet exist - the latest release is OCCT 7.7.
Without [Xw_Window::ProcessMessage()](https://git.dev.opencascade.org/gitweb/?p=occt.git;a=blob;f=src/Xw/Xw_Window.cxx) you'll have to implement a plenty of routines for handling mouse / keyboard events on your own.

I don't recall a dedicated X11 sample for this - OCCT comes with samples using Qt and other GUI frameworks. A low-level X11 event handling could be found in ViewerTest implementation though in legacy OCCT versions.

**Comment by mantielero** [comment]
Ooops, sorry I meant v7.5. In any case I updated the system (now on v7.6). I was reluctant to do so because the wrapping process is not automatic. I will have to fix some functions, but at least now I have ProcessMessage.

**Comment by mantielero** [comment]
Hello again. I managed to wrap `aspect` and `xw` for v7.6. I had lot of difficulties to wrap `ProcessMessage`, but now it is compiling. 

I am getting the following error message:
```
21
(myContext: (), myView: ())
()
17
(myContext: (), myView: ())
()
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  4 (X_DestroyWindow)
  Resource id in failed request:  0x1600002
  Serial number of failed request:  90
  Current serial number in output stream:  90
Error: execution of an external program failed: '/home/jose/src/nimlang/occt.nim/examples/viewer04 '
```

Any idea of where I should look at?

The [Nim code](https://github.com/mantielero/occt.nim/blob/49d973ebf9c680b98593c2e054703a2bc956eed7/examples/viewer04.nim#L95-L110) is compiling. I echo the event type, aViewer and aWindow. So it looks I run the loop twice.

The generated C++ code is [here](https://pastebin.com/Z3hm3Hhn).

**Comment by gkv311** [comment]
Don't know what is actually wrong, but I see two potential issues with Nim code:
- `XSelectInput` is not called from original C++ sample. It is required to activate mouse/keyboard/resize window events to be actually received by X11 event loop.
- Methods `OcctAisHello::ProcessExpose()`, `::ProcessConfigure()` and `::ProcessInput()` in C++ sample override implementation of the base class `AIS_ViewController`, and this is really important for sample to work as expected. I have some doubts that `OcctAisHello` type definition in your Nim code with it's methods declaration like `processExpose()` in actually defines a true C++ subclass with corresponding overridden methods (and not duplicates or redeclarations). But I'm not familiar with Nim.

**Comment by mantielero** [comment]
I finally got it. I had to wait for an update in Nim supporting virtual and override:
![image](https://github.com/gkv311/occt-hello/assets/1116064/8954da8f-9107-4b8c-8a90-ca599326ca57)

THANKS A LOT FOR YOUR PATIENCE.
